# Generated by Django 2.0.5 on 2018-06-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignee',
            name='consignee_sign',
        ),
    ]
