# Generated by Django 2.0.5 on 2018-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='pic_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
