# Generated by Django 2.0.5 on 2018-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_consignee_consignee_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='consignee_sign',
            field=models.IntegerField(default=0),
        ),
    ]
