# Generated by Django 2.0.5 on 2018-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20180529_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic_url',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(),
        ),
    ]
