# Generated by Django 2.0.5 on 2018-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20180529_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic_url',
            field=models.FilePathField(path='/home/xiaojun/PycharmProjects/weixin/WeChatShop/Shop/static/images'),
        ),
    ]
