# Generated by Django 2.0.5 on 2018-06-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20180609_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Shop.consignee'),
        ),
    ]
