# Generated by Django 2.0.5 on 2018-06-09 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_order_order_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.consignee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
