# Generated by Django 2.0.5 on 2018-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20180602_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=150)),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='shopcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField()),
                ('goods_all_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_detail_pic',
            field=models.CharField(default='', max_length=150),
        ),
    ]
