# Generated by Django 2.0.5 on 2018-06-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20180609_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_consignee',
        ),
    ]
