# Generated by Django 2.0.5 on 2018-06-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20180602_0758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='shopcart',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_detail',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_detail_pic',
        ),
    ]
