# Generated by Django 2.0.5 on 2018-06-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_remove_order_order_consignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_sign',
            field=models.BooleanField(default=False),
        ),
    ]
