# Generated by Django 2.0.5 on 2018-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_auto_20180602_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField()),
                ('goods_all_price', models.IntegerField()),
            ],
        ),
    ]
