# Generated by Django 2.0.5 on 2018-06-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_order_order_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0),
        ),
    ]
