# Generated by Django 2.0.5 on 2018-06-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20180610_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_shopcart_number',
            field=models.IntegerField(default=0),
        ),
    ]
