# Generated by Django 2.0.5 on 2018-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_detail_pic',
            field=models.CharField(default='', max_length=150),
        ),
    ]
