# Generated by Django 2.0.5 on 2018-06-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_auto_20180603_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_to_shopcart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Shop.shopcart'),
        ),
    ]
