# Generated by Django 2.0.5 on 2018-06-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_auto_20180610_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_order',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_to_order',
            field=models.ManyToManyField(blank=True, null=True, to='Shop.order'),
        ),
    ]
