# Generated by Django 2.0.5 on 2018-06-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_goods_goods_to_shopcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statue', models.IntegerField(default=-1)),
            ],
        ),
    ]
