# Generated by Django 2.0.5 on 2018-06-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_auto_20180610_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_shopcart',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_to_shopcart',
            field=models.ManyToManyField(blank=True, null=True, to='Shop.shopcart'),
        ),
    ]
