# Generated by Django 2.0.5 on 2018-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statue',
            field=models.NullBooleanField(),
        ),
    ]
