# Generated by Django 2.0.5 on 2018-06-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_auto_20180611_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price_pay',
            field=models.IntegerField(default=0),
        ),
    ]
