# Generated by Django 2.0.5 on 2018-06-12 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_auto_20180612_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.consignee'),
        ),
    ]
