# Generated by Django 2.0.5 on 2018-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_auto_20180603_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_to_order',
            field=models.ForeignKey(default='', on_delete=True, to='Shop.order'),
        ),
    ]
