# Generated by Django 2.0.5 on 2018-06-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_goods_goods_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_to_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Shop.order'),
        ),
    ]
