# Generated by Django 2.0.5 on 2018-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_auto_20180612_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='consignee_id',
            field=models.FloatField(default=0.0),
        ),
    ]
