# Generated by Django 2.0.5 on 2018-06-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_consignee_consignee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_sign',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_order_number',
            field=models.IntegerField(default=0),
        ),
    ]
