# Generated by Django 2.0.5 on 2018-06-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_auto_20180603_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_order',
        ),
    ]
