# Generated by Django 2.0.5 on 2018-06-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_remove_goods_goods_to_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_detail',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_detail_pic',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_shopcart',
        ),
        migrations.DeleteModel(
            name='shopcart',
        ),
    ]
