# Generated by Django 2.0.5 on 2018-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_auto_20180612_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statue',
            field=models.CharField(default='Pendingpayment', max_length=150),
        ),
    ]
