# Generated by Django 2.0.5 on 2018-06-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
