# Generated by Django 2.0.5 on 2018-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_auto_20180612_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statue',
            field=models.CharField(default='待付款', max_length=150),
        ),
    ]
