# Generated by Django 2.0.5 on 2018-06-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_auto_20180613_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='input_money',
            field=models.IntegerField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0, max_length=159),
        ),
        migrations.AddField(
            model_name='user',
            name='output_money',
            field=models.IntegerField(default=0, max_length=150),
        ),
    ]
