# Generated by Django 2.0.5 on 2018-06-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_auto_20180613_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(default='', max_length=159),
        ),
    ]
