# Generated by Django 2.0.5 on 2018-06-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_goods_goods_to_shopcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statue', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shop.User')),
            ],
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='goods_all_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='goods_number',
            field=models.IntegerField(default=0),
        ),
    ]
