# Generated by Django 2.0.5 on 2018-06-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0023_auto_20180603_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_to_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Shop.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='add',
            field=models.CharField(default='', max_length=150),
        ),
    ]
