# Generated by Django 2.0.5 on 2018-06-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0023_order_pay_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='input_money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='output_money',
        ),
    ]
