# Generated by Django 2.0.5 on 2018-06-06 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0024_auto_20180603_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=150)),
                ('consignee_address', models.CharField(max_length=150)),
                ('consignee_phone', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='add',
            new_name='order_consignee',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_order',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.order'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_to_order_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Shop.order_detail'),
        ),
    ]
