# Generated by Django 2.0.5 on 2018-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0027_order_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jifen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
