# Generated by Django 2.0.5 on 2018-06-13 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0028_auto_20180613_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_to_user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
