# Generated by Django 2.0.5 on 2018-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0029_goods_goods_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sale',
            field=models.IntegerField(default=0),
        ),
    ]
