# Generated by Django 2.0.5 on 2018-06-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0029_auto_20180607_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='shopcart_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
