# Generated by Django 2.0.5 on 2018-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0030_shopcart_shopcart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='shopcart_id',
            field=models.CharField(max_length=150),
        ),
    ]
