# Generated by Django 2.0.5 on 2018-06-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0030_goods_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=150)),
                ('comment_content', models.TextField(default='')),
                ('comment_time', models.DateField(auto_now_add=True)),
                ('comment_level', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='statue',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_to_consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.consignee'),
        ),
        migrations.AddField(
            model_name='goods',
            name='statue',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='order_detail',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_goods',
            field=models.ForeignKey(on_delete=True, to='Shop.goods'),
        ),
    ]
