# Generated by Django 2.0.5 on 2018-06-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0031_auto_20180613_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodscopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statue', models.CharField(default='', max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=150)),
                ('goods_shopcart_number', models.IntegerField(default=0)),
                ('goods_order_number', models.IntegerField(default=0)),
                ('goods_to_consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.consignee')),
                ('goods_to_order', models.ManyToManyField(blank=True, null=True, to='Shop.order')),
                ('goods_to_shopcart', models.ManyToManyField(blank=True, null=True, to='Shop.shopcart')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_order_number',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_shopcart_number',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_consignee',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_order',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_to_shopcart',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='statue',
        ),
    ]
