# Generated by Django 2.0.5 on 2018-06-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0031_auto_20180608_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='goods_all_price',
            field=models.FloatField(blank=True),
        ),
    ]
