# Generated by Django 2.0.5 on 2018-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0032_auto_20180608_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='goods_all_price',
            field=models.IntegerField(blank=True),
        ),
    ]
