# Generated by Django 2.0.5 on 2018-06-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0032_auto_20180613_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='goodscopy',
            name='goods_to_consignee',
        ),
        migrations.RemoveField(
            model_name='goodscopy',
            name='goods_to_order',
        ),
        migrations.RemoveField(
            model_name='goodscopy',
            name='goods_to_shopcart',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_shopcart_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_to_order',
            field=models.ManyToManyField(blank=True, null=True, to='Shop.order'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_to_shopcart',
            field=models.ManyToManyField(blank=True, null=True, to='Shop.shopcart'),
        ),
        migrations.AddField(
            model_name='order',
            name='statue',
            field=models.CharField(default='待付款', max_length=150),
        ),
        migrations.DeleteModel(
            name='goodscopy',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.order'),
        ),
    ]
