# Generated by Django 2.0.5 on 2018-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0033_auto_20180613_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_goods',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_goods',
            field=models.ManyToManyField(blank=True, null=True, to='Shop.goods'),
        ),
    ]
