# Generated by Django 2.0.5 on 2018-06-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0033_auto_20180608_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopcart_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
