# Generated by Django 2.0.5 on 2018-06-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0034_user_shopcart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_shopcart_number',
            field=models.IntegerField(default=1),
        ),
    ]
