# Generated by Django 2.0.5 on 2018-06-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0035_goods_goods_shopcart_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='goods_all_price',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='goods_number',
        ),
    ]
