# Generated by Django 2.0.6 on 2018-06-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0036_goods_pic_url_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_detail',
        ),
    ]
