# Generated by Django 2.0.6 on 2018-06-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0037_remove_goods_goods_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='desc',
        ),
    ]
