# Generated by Django 2.0.5 on 2018-06-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0037_shopcart_goods_all_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='goods_all_price',
            field=models.IntegerField(blank=True),
        ),
    ]
