from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from Shop import views

urlpatterns = [
    path('index.html', views.index),
    path('member.html', views.member),
    path('step.html', views.step),
    path('about.html', views.about),
    path('infor.html', views.infor),
    path('saftystep.html', views.saftystep),
    path('login.html', views.mylogin, name='login'),
    path('logout', views.mylogout, name='logout'),
    path('shopcart.html', views.shopcart, name='shopcart'),
    path('allorder.html', views.allorder),
    path('message.html', views.message),
    path('address.html', views.address),
    path('application.html', views.application),
    path('applicationjob.html', views.applicationjob),
    path('applicationjob.html', views.applicationjob),
    path('boundphone.html', views.boundphone),
    path('category.html', views.category),
    path('city.html', views.city),
    path('collect.html', views.collect),
    path('collect-edit.html', views.collect_edit),
    path('contact.html', views.contact),
    url('detail-(?P<goods_id>\d+).html', views.detail, name='detail'),
    path('forgetpassword.html', views.forgetpassword),
    path('gladdress.html', views.gladdress),
    path('integral.html', views.integral),
    path('integralexchange.html', views.integralexchange),
    path('integralrecords.html', views.integralrecords),
    path('job.html', views.job),
    path('list.html', views.list),
    path('messdetail.html', views.messdetail),
    path('messdetailactive.html', views.messdetailactive),
    path('money.html', views.money),
    path('mymessage.html', views.mymessage),
    path('myrecommend.html', views.myrecommend),
    path('news.html', views.news),
    path('newsdetail.html', views.newsdetail),
    path('order.html', views.order),
    path('orderdetail.html', views.orderdetail),
    path('password.html', views.password, name="password"),
    path('pay.html', views.pay),
    path('payment.html', views.payment),
    path('recharge.html', views.recharge),
    path('recommend.html', views.recommend),
    path('records.html', views.records),
    path('reg.html', views.reg),
    path('release.html', views.release),
    path('speed.html', views.speed),
    path('step.html', views.step),
    path('tidings.html', views.tidings),
    url('tureorder.html', views.tureorder, name='tureorder'),
    path('village.html', views.village),
    path('ygq.html', views.ygq),
    path('yhq.html', views.yhq),
    url(r'shopcart-add/goods_id=(?P<goods_id>\d+)/goods_number=(?P<goods_number>\d+).html', views.shopcart_add, name="shopcart_a")
]

