from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from Shop import views

urlpatterns = [
    path('', views.index),
    path('delorder', views.delorder),
    path('delcollect', views.delcollect),
    path('deladdress', views.deladdress),
    path('cancelorder', views.cancelorder),
    path('index.html', views.index),
    path('member.html', views.member),
    path('step.html', views.step),
    path('about.html', views.about),
    path('infor.html', views.infor),
    path('saftystep.html', views.saftystep),
    path('login.html', views.mylogin, name='login'),
    path('logout', views.mylogout, name='logout'),
    path('shopcart.html', views.shopcart_views, name='shopcart'),
    path('allorder.html', views.allorder),
    path('message.html', views.message),
    path('address.html', views.address),
    path('category.html', views.category_views),
    path('collect.html', views.collect),
    path('collect-edit.html', views.collect_edit),
    path('contact.html', views.contact),
    url('detail-(?P<goods_id>\d+).html', views.detail, name='detail'),
    path('forgetpassword.html', views.forgetpassword),
    path('gladdress.html', views.gladdress),
    path('integral.html', views.integral),
    path('integralexchange.html', views.integralexchange),
    path('integralrecords.html', views.integralrecords),
    path('messdetail.html', views.messdetail),
    path('money.html', views.money),
    path('myrecommend.html', views.myrecommend),
    path('news.html', views.news),
    path('order.html', views.order_views),
    path('orderdetail.html', views.orderdetail),
    path('password.html', views.password, name="password"),
    path('pay.html', views.pay),
    path('payment.html', views.payment),
    path('recharge.html', views.recharge),
    path('recommend.html', views.recommend),
    path('records.html', views.records),
    path('reg.html', views.reg),
    path('step.html', views.step),
    path('tidings.html', views.tidings),
    path('tureorder.html', views.tureorder, name='tureorder'),
    path('ygq.html', views.ygq),
    path('yhq.html', views.yhq),
    path('comment.html',views.comment_views)
]

